<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('document_qr_codes', function (Blueprint $table) {
            $table->id();

            /*
            |--------------------------------------------------------------------------
            | Unique QR identity
            |--------------------------------------------------------------------------
            */

            $table->uuid('qr_token')->unique();

            /*
            |--------------------------------------------------------------------------
            | QR lifecycle
            |--------------------------------------------------------------------------
            |
            | unused      = generated/printed but not yet registered
            | registered  = already linked to a document
            | void        = cancelled / unusable QR
            |
            */

            $table->string('status', 20)
                ->default('unused');

            /*
            |--------------------------------------------------------------------------
            | Linked document
            |--------------------------------------------------------------------------
            */

            $table->foreignId('document_id')
                ->nullable()
                ->unique()
                ->constrained('documents')
                ->nullOnDelete();

            /*
            |--------------------------------------------------------------------------
            | Generated By
            |--------------------------------------------------------------------------
            */

            $table->foreignId('generated_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->timestamp('generated_at')
                ->nullable();

            $table->timestamp('registered_at')
                ->nullable();

            $table->timestamps();

            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('document_qr_codes');
    }
};