<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class DocumentQrCode extends Model
{
    protected $fillable = [
        'qr_token',
        'status',
        'document_id',
        'generated_by',
        'generated_at',
        'registered_at',
    ];

    protected function casts(): array
    {
        return [
            'generated_at' => 'datetime',
            'registered_at' => 'datetime',
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Document
    |--------------------------------------------------------------------------
    */

    public function document(): BelongsTo
    {
        return $this->belongsTo(
            Document::class,
            'document_id'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Generated By
    |--------------------------------------------------------------------------
    */

    public function generatedBy(): BelongsTo
    {
        return $this->belongsTo(
            User::class,
            'generated_by'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Helpers
    |--------------------------------------------------------------------------
    */

    public function isUnused(): bool
    {
        return $this->status === 'unused';
    }

    public function isRegistered(): bool
    {
        return $this->status === 'registered';
    }

    public function isVoid(): bool
    {
        return $this->status === 'void';
    }
}